# fly.toml app configuration file generated for weatherman-d-t-4-1719232232-client on 2024-06-24T12:31:15Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'weatherman-d-t-4-1719232232-client'
primary_region = 'mia'

[build]

[http_service]
  internal_port = 8043
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 4
